# Generated by Django 6.0.1 on 2026-01-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_patient_address_alter_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
