# Generated by Django 6.0.1 on 2026-01-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patient_height_patient_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacist',
            name='gender',
        ),
    ]
