# Generated by Django 6.0 on 2026-01-14 15:04

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=main.models.doctor_profile_image_path),
        ),
    ]
